services:
  
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  rq-worker:
    build: .
    command: rq worker --url redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis